[point_colours]
hover = [235, 52, 61]
moving = [235, 216, 52]
ahead = [55, 235, 52]
diverge = [52, 140, 235]
boundary = [255,255,255]

[track_colours]
route_colour = [235, 216, 52]
base_colour = [255, 255, 255]
highlight_colour = [255, 0, 0]

[serial]
port = 'COM4'
baud = 9600